---
title: "Preparación de datos"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: show  
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      echo = TRUE 
                      )
options(scipen=9999) # desactivar notacion cientifica
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

## Librerías

```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos 
               haven,       # importar datos en .dta o .sav
               car,         # recodificar variables
               sjlabelled,  # etiquetado de variables
               sjmisc,      # descriptivos y frecuencias
               sjPlot,      # tablas, plots y descriptivos
               summarytools,# resumen de dataframe
               stringr
               )
```

## Datos

```{r}
df_pubs <- read.csv(here::here("input/data/original/bd_pub_2013_2021.csv"),
                    encoding = "UTF-8",stringsAsFactors = T)

# ajustar nombres de variables 
names(df_pubs) <- 
  names(df_pubs) %>%
  tolower() %>%
  str_replace_all(c(
    "á" = "a",
    "é" = "e",
    "í" = "i",
    "ó" = "o",
    "u" = "u",
    "ñ" = "n",
    "/" = "_",
    "\\(" = " ",
    "\\)" = " ",
    "%"= " ",
    "\\." = ""
  ))

```


```{r}
# filtrar la base por WOS y Scopus
df_wos_scopus <-
  df_pubs %>%
  #creamos un id unico para cada publicacion
  tibble::rownames_to_column(var = "id") %>%
  #filtramos por WOS y Scopus
  dplyr::filter(indexacion %in% c("WoS","WOS","Scopus")) %>% 
  # limpiamos el string de DOI y creamos uno nuevo.
  mutate(doi=str_replace_all(doiisbnlink,c("doi.org/"="",
                                           "https://" = "",
                                           "http://" = "",
                                           "dx." = "",
                                           "DOI: "="",
                                           "DOI "= "",
                                           "DOI"= "",
                                           "doi:"="",
                                           ":"= "",
                                           " "="",
                                           " "="",
                                           "www."=""))) %>% 
  #seleccionamos y ordenamos
  select(id,indexacion,doi,doiisbnlink,anoreporteanid,anopublicacion,everything()) %>% 
  arrange(desc(indexacion),doi)

sjmisc::frq(df_wos_scopus$indexacion)

# hay duplicados?
frq_1<- sjmisc::frq(df_wos_scopus$doi) %>% 
  as.data.frame()
frq_1 %>% filter(frq>=2) # Hay varios
sjmisc::frq(is.na(df_wos_scopus$doi)) #sin nada

df_wos_scopus_clean <-  df_wos_scopus[rev(!duplicated(rev(df_wos_scopus$doi),incomparables = NA)),]

frq_2<- sjmisc::frq(df_wos_scopus_clean$doi) %>% 
  as.data.frame()
frq_2 %>% filter(frq>=2) # OK, sin duplicados
row.names(df_wos_scopus_clean) <- NULL #reset rownames
```


```{r}
# metricas de publicaciones y journals

# fuente: https://cran.r-project.org/web/packages/roadoi/vignettes/intro.html
# install.packages("roadoi")

publication_info_wos_scopus <-
  roadoi::oadoi_fetch(dois = df_wos_scopus_clean$doi,
                      email = "julioiturrasanhueza@gmail.com",
                      .progress = "text")


publication_info_wos<- 
  roadoi::oadoi_fetch(dois = df_wos_scopus_clean$doi[df_wos_scopus_clean$indexacion=="WoS"],
                      email = "julioiturrasanhueza@gmail.com",
                      .progress = "text")

publication_info_socpus<- 
  roadoi::oadoi_fetch(dois = df_wos_scopus_clean$doi[df_wos_scopus_clean$indexacion=="Scopus"],
                      email = "julioiturrasanhueza@gmail.com",
                      .progress = "text")


#unificamos para identificar missing = DOI con problemas
df_info <- publication_info %>% select(doi,title,year)
df_coes <- df_wos_scopus_clean %>% select(id,doi,titulo,anopublicacion)
doi_faltantes <- full_join(df_coes,df_info) 
#Entonces, revisamos los NA en title,
#identificar los faltantes. Los que tienen NA en title:
#explicacioon: al usar la funcion para buscar info, usa el DOI, si el DOI esta malo, no encuentra nada.
table(is.na(doi_faltantes$title))

#creamos variable para marcar papers a revisar:
doi_faltantes$revisar_doi <- ifelse(test = is.na(doi_faltantes$title),
                                    yes = "REVISAR DOI", 
                                    no = "NO REVISAR DOI ")
table(doi_faltantes$revisar_doi)
xlsx::write.xlsx(doi_faltantes,file = here::here("output/doi_faltantes.xlsx"))
```

```{r}
#cargar base con IF
df_if <-data.table::fread(file = here::here("input/data/original/factor_impacto.csv"),stringsAsFactors =T)
#ajustar nombres
names(df_if) <- c("rank","journal_name_lower","total_cites","impactfactor","eigenfactor")
#nombres lowercase
df_if$journal_name_lower <- tolower(df_if$journal_name_lower)
publication_info_wos_scopus$journal_name_lower <-tolower(publication_info_wos_scopus$journal_name) 


#merge usando variable nombre en lowercase
#falta depurar nombres con ñ o tildes, pueden recuperarse mas.
df_doi_if<- left_join(publication_info_wos_scopus,
                      df_if, 
                      by ="journal_name_lower")
```


```{r}
# fuente: https://cran.r-project.org/web/packages/JCRImpactFactor/JCRImpactFactor.pdf
# install.packages("JCRImpactFactor")
journal_if <- JCRImpactFactor::find.IF.JCR(publication_info$journal_name, year=2019)
```


# Guardar datos

```{r}
# save(df_wos_scopus_clean,file = "../input/data/proc/df_wos_scopus.Rdata")
```



